[project]
name = "flight-delays"
version = "0.1.0"
description = "Download and analyze flight delay and weather data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "airportsdata>=20250909",
    "dask>=2025.9.1",
    "ipykernel>=6.30.1",
    "joblib>=1.4.2",
    "matplotlib>=3.9.0",
    "meteostat>=1.7.4",
    "numpy>=2.1.0",
    "pandas>=2.3.2",
    "pandas-stubs>=2.0.0",
    "pyarrow>=21.0.0",
    "scikit-learn>=1.5.0",
    "seaborn>=0.13.0",
    "tqdm>=4.67.1",
    "torch>=2.0.0",
]
